version: "3.7"
services:
  mysql8019:
    image: "mysql:8.0.19"
    ports:
      - "3306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "SP500"
      MYSQL_PASSWORD: "root1234"
    volumes:
      - ./init.sql:/data/application/init.sql
  sp500:
    build: .
    command: sh -c "./wait-for.sh mysql8019:3306 -- ./sp500_straddle"
    depends_on:
      - mysql8019
    ports:
      - "8888:8888"